<?php
// ELMS: Requirement Dashboard OG
// Development Sponsored by The Pennsylvania State University
// ELMS is Copyright (C) 2008-2012  The Pennsylvania State University
//
// Bryan Ollendyke
// bto108@psu.edu
//
// Keith D. Bailey
// kdb163@psu.edu
//
// 12 Borland
// University Park,  PA 16802

/**
 * @file
 * Add requirement dashboards to og and implement common requirements
 */

/**
 * Implements hook_requirement_dashboard_provider().
 */
function requirement_dashboard_og_requirement_dashboard_provider() {
  $dashboards['og'] = array(
    'title' => t('Group stats'),
    'path' => 'node/%node/og_stats',
  );
  return $dashboards;
}

/**
 * Implements hook_dashboard_requirements().
 */
function requirement_dashboard_og_dashboard_requirements($provider) {
  $requirements = array();
  switch ($provider) {
    case 'og':
      $tmp = og_context();
      $group = node_load($tmp['gid']);
      $requirements['name'] = array(
        'title' => t('Group name'),
        'value' => $group->title,
        'severity' => REQUIREMENT_INFO,
      );
      if (isset($group->body)) {
        $requirements['description'] = array(
          'title' => t('Description'),
          'value' => $group->body,
          'severity' => REQUIREMENT_INFO,
        );
      }
      // if theme is set then list the theme used
      if (isset($group->group_theme['und'][0]['value'])) {
        $requirements['theme'] = array(
          'title' => t('Theme'),
          'value' => $group->group_theme['und'][0]['value'],
          'severity' => REQUIREMENT_INFO,
        );
      }
      break;
  }
  return $requirements;
}

/**
 * Implements hook_menu_alter().
 */
function requirement_dashboard_og_menu_alter(&$items) {
  if (isset($items['node/%node/og_stats'])) {
    $items['node/%node/og_stats']['access callback'] = 'requirement_dashboard_og_status_access';
    $items['node/%node/og_stats']['access arguments'] = array(1);
  }
}

/**
 * Callback to only implement on group types
 */
function requirement_dashboard_og_status_access($node) {
  return og_is_group_type('node', $node->type) ? user_access('view og requirements dashboard') : FALSE;
}
