#!/bin/sh
#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Michael Boelen <michael@rootkit.nl>
# PLUGIN_CATEGORY=Data
# PLUGIN_DESC=Webserver data analysis
# PLUGIN_NAME=webserver_data
#-----------------------------------------------------
#########################################################################
#
# Test: search default names, like test, sample, samples

