<?php
// ELMS: Spaces Theme
// Development Sponsored by The Pennsylvania State University
// ELMS is Copyright (C) 2008-2012  The Pennsylvania State University
//
// Bryan Ollendyke
// bto108@psu.edu
//
// Keith D. Bailey
// kdb163@psu.edu
//
// 12 Borland
// University Park,  PA 16802

/**
 * @file
 * Functions to enable more granular theme settings per space.
 */

/**
 * Implements hook_init().
 */
function spaces_theme_init() {
  // only add these settings to the node/%theme page
  if (arg(0) == 'theme' || (arg(0) == 'node' && arg(2) == 'theme')) {
    drupal_add_js(drupal_get_path('module', 'spaces_theme') . '/spaces_theme.js');
  }
}
/**
 * Implements hook_menu().
 */
function spaces_theme_menu() {
  $items = array();
  $items['node/%node/theme'] = array(
    'title' => 'Theme',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_spaces_theme_theme_form'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'spaces_og_access_admin',
    'access arguments' => array(1),
    'file' => 'spaces_theme.theme.inc',
    'file path' => drupal_get_path('module', 'spaces_theme') . '/inc',
  );
  return $items;
}

// only display tab on group form
function _spaces_theme_og_theme_access() {
  $node = menu_get_object();
  // account for weird og glitch where it won't load
  if (arg(2) == 'group') {
    $node = node_load(arg(1));
  }
   // if this is the group node, then assess if they are an admin of the group
  if (isset($node->type) && og_is_group_type('node', $node->type)) {
    return og_user_access('node', $node->nid, 'administer group');
  }
  return 0;
}
