<?php

include_once 'elms_reference_links.features.inc';

/**
 * Implements hook_define_highlight_relationship_alter().
 */
function elms_reference_links_define_highlight_relationship_alter(&$relationships) {
  if (spaces_access_feature('view', 'elms_reference_links')) {
    $relationships['enhance_content']['highlight_types']['content_links'] = array(
      'id' => 'links',
      'ref_field' => 'field_related_content_ref',
      'text_field' => 'title',
      'icon' => drupal_get_path('module', 'elms_reference_links') . '/images/link.png',
      'display_text' => t('Add Related Links'),
    );
  }
}
