<?php
/**
 * @file
 * Textbook Style Guide
 */

/**
 * Implementation of hook_init().
 */
function textbook_init() {
  // include style guide sheets on nodes
  if (arg(0) == 'node') {
    // get base path to css
    $tpath = drupal_get_path('module', 'textbook') .'/css/';
    // add the reset style
    drupal_add_css($tpath .'reset.css');
    // add the base level textbook styles
    drupal_add_css($tpath .'textbook.css', array('group' => CSS_THEME, 'weight' => 100));
    // include collapse so it can be used in node bodies
    drupal_add_js('misc/collapse.js');
  }
  // ensure that print styles are included on print
  if (arg(0) == 'print') {
    $tpath = drupal_get_path('module', 'textbook') .'/css/';
    drupal_add_css($tpath .'print.css');
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function textbook_wysiwyg_editor_settings_alter(&$settings, $context) {
  // settings known to be ok for CKEditor
  if ($context['profile']->editor == 'ckeditor') {
    $settings['undoStackSize'] = 40; // increase the undo history
    $settings['fillEmptyBlocks'] = FALSE;
    $settings['stylesSet'] = _textbook_styles(); // apply our styles
  }
}

/**
 * Helper function for defining styles
 */
function _textbook_styles() {
  $styles = array(
    array(
      'name' => 'DIV Center',
      'element' => 'div',
      'attributes' => array(
        'class' => 'textbook_center'
      ),
    ),
    array(
      'name' => 'DIV Right',
      'element' => 'div',
      'attributes' => array(
        'class' => 'textbook_right'
      ),
    ),
    array(
      'name' => 'Emphasis (italic)',
      'element' => 'em',
    ),
    array(
      'name' => 'Strong (bold)',
      'element' => 'strong',
    ),
    array(
      'name' => 'Superscript',
      'element' => 'sup',
    ),
    array(
      'name' => 'Subscript',
      'element' => 'sub',
    ),
    array(
      'name' => 'Color 1',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color1',
      )
    ),
    array(
      'name' => 'Color 2',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color2',
      )
    ),
    array(
      'name' => 'Color 3',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color3',
      )
    ),
    array(
      'name' => 'Color 4',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color4',
      )
    ),
    array(
      'name' => 'Color 5',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color5',
      )
    ),
    array(
      'name' => 'Color 6',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color6',
      )
    ),
  );
  return $styles;
}