<?php

include_once 'elms_timeline.features.inc';

/**
 * Implements hook_define_highlight_relationship_alter().
 */
function elms_timeline_define_highlight_relationship_alter(&$relationships) {
  if (spaces_access_feature('view', 'elms_timeline')) {
    $relationships['enhance_content']['highlight_types']['timeline_item'] = array(
      'id' => 'timeline',
      'ref_field' => 'field_timeline_content_ref',
      'text_field' => 'field_timeline_text_ref',
      'icon' => drupal_get_path('module', 'elms_timeline') . '/images/timeline.png',
      'display_text' => t('Add a Time point'),
    );
  }
}


/**
 * Implements hook_views_plugins_alter().
 */
function elms_timeline_views_plugins_alter(&$plugins) {
  // Prevent the timeline module from displaying when empty
  $plugins['style']['timeline']['even empty'] = FALSE;
}
